apiVersion: v1
kind: Service
metadata:
  name: dcpf-press
  namespace: assurance
spec:
  selector:
    app: dcpf-press
  ports:
    - protocol: TCP
      port: 1880
      targetPort: 1880
      nodePort: 30026
  type: NodePort