apiVersion: v1
kind: Service
metadata:
  name: dcpf-camera
  namespace: assurance
spec:
  selector:
    app: dcpf-camera
  ports:
    - protocol: TCP
      port: 1880
      targetPort: 1880
      nodePort: 30024
  type: NodePort