apiVersion: v1
kind: Service
metadata:
  name: dcpf-database-serv
  namespace: assurance
spec:
  selector:
    app: dcpf-database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30000
  type: NodePort

