apiVersion: v1
kind: Service
metadata:
  name: dcpf-rotator
  namespace: assurance
spec:
  selector:
    app: dcpf-rotator
  ports:
    - protocol: TCP
      port: 1880
      targetPort: 1880
      nodePort: 30021
  type: NodePort