apiVersion: v1
kind: Service
metadata:
  name: dcpf-orders
  namespace: assurance
spec:
  selector:
    app: dcpf-orders
  ports:
    - protocol: TCP
      port: 1880
      targetPort: 1880
      nodePort: 30019
  type: NodePort