apiVersion: v1
kind: Service
metadata:
  name: dcpf-assembler
  namespace: assurance
spec:
  selector:
    app: dcpf-assembler
  ports:
    - protocol: TCP
      port: 1880
      targetPort: 1880
      nodePort: 30025
  type: NodePort