apiVersion: v1
kind: Service
metadata:
  name: dcpf-execsystem
  namespace: assurance
spec:
  selector:
    app: dcpf-execsystem
  ports:
    - protocol: TCP
      port: 1880
      targetPort: 1880
      nodePort: 30020
  type: NodePort