apiVersion: v1
kind: Service
metadata:
  name: dcpf-magazine
  namespace: assurance
spec:
  selector:
    app: dcpf-magazine
  ports:
    - protocol: TCP
      port: 1880
      targetPort: 1880
      nodePort: 30016
  type: NodePort