apiVersion: v1
kind: Service
metadata:
  name: dcpf-conveyorbelt
  namespace: assurance
spec:
  selector:
    app: dcpf-conveyorbelt
  ports:
    - protocol: TCP
      port: 1880
      targetPort: 1880
      nodePort: 30017
  type: NodePort