apiVersion: v1
kind: Service
metadata:
  name: dcpf-drill
  namespace: assurance
spec:
  selector:
    app: dcpf-drill
  ports:
    - protocol: TCP
      port: 1880
      targetPort: 1880
      nodePort: 30022
  type: NodePort