apiVersion: v1
kind: Service
metadata:
  name: dcpf-customiiot
  namespace: assurance
spec:
  selector:
    app: dcpf-customiiot
  ports:
    - protocol: TCP
      port: 1880
      targetPort: 1880
      nodePort: 30027
  type: NodePort