apiVersion: apps/v1
kind: Deployment
metadata:
  name: dcpf-magazine
  namespace: assurance
  labels:
    app: dcpf-magazine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dcpf-magazine
  template:
    metadata:
      labels:
        app: dcpf-magazine
    spec:
      containers:
      - name: dcpf-magazine
        image: nodered/node-red:latest
        ports:
        - containerPort: 1880
        env:
        - name: NRADM_USER
          value: nradm
        - name: NRADM_PASS
          value: nradmpass
        - name: CFG_ACL_ENDP
          value: https://ServiceNodeDefaultACL:1880/acl
        - name: CFG_ACL_CACE
          value: /data/ca.pem
        - name: NRLIB_ENDP
          value: https://DefaultTransformationLibrary:1880/
        - name: NRLIB_USER
          value: nruser
        - name: NRLIB_PASS
          value: nrpass
        - name: NRLIB_CACE
          value: /data/ca.pem
        - name: AISRV_ENDP
          value: https://DefaultAIServer:8080/nodes
        - name: AISRV_CACE
          value: /data/ca.pem
        - name: FLUME_LEVEL
          value: debug
        - name: FLUME_HOST
          value: DefaultFlumeNode
        - name: FLUME_PORT
          value: '9563'
        - name: FLUME_METRICS
          value: 'false'
        - name: FLUME_AUDIT
          value: 'false'
        - name: OTEL_EXPORTER
          value: http://jaeger:4318/v1/traces
        - name: OTEL_SERVICE
          value: DCPF-Magazine
        - name: OTEL_PREFIX
          value: DCPF-Magazine-
        volumeMounts:
        - mountPath: /data
          name: dcpf-magazine
      initContainers:
      - name: dcpf-magazine-init
        image: busybox:latest
        volumeMounts:
        - mountPath: /data
          name: dcpf-magazine
        command: [ 'sh', '-c', 'cd / && wget -O dockervolumebackup.tar "https://drive.google.com/uc?export=download&id=1mqF6cf34XCCC3Zm2BVLh1q6_gWeHZ3ki" && tar xvf dockervolumebackup.tar ']
      volumes:
      - name: dcpf-magazine
        emptyDir: