apiVersion: v1
kind: Service
metadata:
  name: defaulttransformationlibrary
  namespace: assurance
spec:
  selector:
    app: defaulttransformationlibrary
  ports:
    - protocol: TCP
      port: 1880
      targetPort: 1880
      nodePort: 30003
  type: NodePort

