apiVersion: apps/v1
kind: Deployment
metadata:
  name: defaulttransformationlibrary
  namespace: assurance
  labels:
    app: defaulttransformationlibrary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: defaulttransformationlibrary
  template:
    metadata:
      labels:
        app: defaulttransformationlibrary
    spec:
      containers:
      - name: defaulttransformationlibrary
        image: nodered/node-red:latest
        ports:
        - containerPort: 1880
        volumeMounts:
        - mountPath: /data
          name: defaulttransformationlibrary
      initContainers:
      - name: defaulttransformationlibrary-init
        image: busybox:latest
        volumeMounts:
        - mountPath: /data
          name: defaulttransformationlibrary
        command: [ 'sh', '-c', 'cd / && wget https://github.com/mircosoderi/State-of-the-art-Artifacts-for-Big-Data-Engineering-and-Analytics-as-a-Service/raw/main/transformationlibrary.tar && tar xvf transformationlibrary.tar ']
      volumes:
      - name: defaulttransformationlibrary
        emptyDir: