apiVersion: v1
kind: Service
metadata:
  name: servicenodedefaultacl
  namespace: assurance
spec:
  selector:
    app: servicenodedefaultacl
  ports:
    - protocol: TCP
      port: 1880
      targetPort: 1880
      nodePort: 30002
  type: NodePort

